language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  allow_failures:
  - python: "3.8"
  - python: "3.9"

before_install:
  - pip install -U pip

install:
  - pip install --quiet tensorflow
  - pip install --quiet torch
  - pip install nbformat ipython pylint;
  - pip install .

script:
  - pytest tests/commit

after_success:
  - pip show pylint
  - pylint --rcfile=./demos/.pylintrc demos
  - pylint --rcfile=./tests/.pylintrc tests
  - pylint --rcfile=./phi/.pylintrc phi
